//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_Dn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUAT
    {
        public string ma_ctphieuxuat { get; set; }
        public string ma_ctphieunhap { get; set; }
        public string ma_khachhang { get; set; }
        public int soluongxuat { get; set; }
        public int soluongthucxuat { get; set; }
        public string ghichu { get; set; }
        public string nguoitao { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ma_phieuxuat { get; set; }
    
        public virtual CHITIETPHIEUNHAP CHITIETPHIEUNHAP { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
