//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_Dn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETPHIEUNHAP()
        {
            this.CHITIETPHIEUXUATs = new HashSet<CHITIETPHIEUXUAT>();
        }
    
        public string ma_ctphieunhap { get; set; }
        public int soluongnhap { get; set; }
        public int soluongthuc { get; set; }
        public int soluongton { get; set; }
        public Nullable<double> gianhap { get; set; }
        public Nullable<double> giaxuat { get; set; }
        public string ghichu { get; set; }
        public string ma_phieunhap { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ma_mathang { get; set; }
        public string nguoitao { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
    }
}
