//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_Dn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string ma_nhanvien { get; set; }
        public string ten_nhanvien { get; set; }
        public string ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public Nullable<int> ma_quyen { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
